/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCallC */

#ifndef _Included_JavaCallC
#define _Included_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCallC
 * Method:    keyboardBlockerOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCallC_keyboardBlockerOn
  (JNIEnv *, jclass);

/*
 * Class:     JavaCallC
 * Method:    keyboardBlockerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCallC_keyboardBlockerOff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
